use super::*;

pub(crate) fn test_app_state() -> AppState {
    AppState {
        requests: Mutex::new(Vec::new()),
        session_request_totals: Mutex::new(HashMap::new()),
        hook_waiters: Mutex::new(HashMap::new()),
        auto_approve_sessions: Mutex::new(HashSet::new()),
        approval_rules: Mutex::new(Vec::new()),
        risk_guard_enabled: Mutex::new(true),
        compact_width: Mutex::new(COMPACT_WINDOW_WIDTH),
        compact_left_width: Mutex::new(0.0),
        presentation_generation: Arc::new(AtomicU64::new(0)),
        shape_pulse_generation: Arc::new(AtomicU64::new(0)),
        home_bounds: Mutex::new(None),
        notch_metrics: Mutex::new(NotchMetrics::default()),
        session_last_seen: Mutex::new(HashMap::new()),
        session_retention_secs: Mutex::new(DEFAULT_SESSION_RETENTION_SECS),
        subagent_retention_secs: Mutex::new(DEFAULT_SUBAGENT_RETENTION_SECS),
        session_token_usage: Mutex::new(HashMap::new()),
        session_token_usage_by_model: Mutex::new(HashMap::new()),
        session_agent_map: Mutex::new(HashMap::new()),
        token_usage_file_offsets: Mutex::new(HashMap::new()),
        token_usage_day: Mutex::new(current_local_day_key()),
        startup_daily_floor: Mutex::new(TokenUsage::default()),
        startup_daily_floor_by_model: Mutex::new(HashMap::new()),
        absolute_token_sessions: Mutex::new(HashSet::new()),
        daily_tokens_baseline: Mutex::new(TokenUsage::default()),
        known_sessions: Mutex::new(HashMap::new()),
        pinned_sessions: Mutex::new(HashSet::new()),
        previous_app_pid: Mutex::new(None),
        last_listening_online: Mutex::new(None),
        last_hook_health: Mutex::new(None),
        bridge_port: AtomicU16::new(0),
        bridge_auth_token: Mutex::new(uuid::Uuid::new_v4().to_string()),
        last_bridge_reachable: Mutex::new(None),
        active_subagents: Mutex::new(Vec::new()),
        cursor_subagent_conversations: Mutex::new(HashMap::new()),
        cursor_lifecycle_token_sessions: Mutex::new(HashSet::new()),
        last_subagent_snapshot_emit: Mutex::new(Instant::now() - Duration::from_secs(10)),
        snapshot_debounce_generation: AtomicU64::new(0),
        snapshot_debounce_worker_running: AtomicBool::new(false),
        last_subagent_reconcile: Mutex::new(Instant::now() - Duration::from_secs(10)),
        last_hook_activity: Mutex::new(Instant::now()),
        token_history_dirty: AtomicBool::new(false),
        transcript_cache: Mutex::new(TranscriptCache::default()),
        media_card_enabled: Mutex::new(true),
        artwork_backdrop_enabled: Mutex::new(false),
        bluetooth_battery_card_enabled: Mutex::new(false),
        bluetooth_battery_alert_enabled: Mutex::new(false),
        bluetooth_battery_alert_threshold: Mutex::new(20),
        gatt_battery_cache: Mutex::new(crate::gatt_battery::GattProbeCache::default()),
        clipboard_history: Mutex::new(Vec::new()),
        clipboard_history_limit: Mutex::new(clipboard_history::DEFAULT_MAX_ENTRIES),
        clipboard_history_enabled: Mutex::new(false),
        clipboard_auto_stage: Mutex::new(false),
        file_station: Mutex::new(Vec::new()),
        lyrics_enabled: Mutex::new(false),
        lyrics: Mutex::new(None),
        lyrics_track_key: Mutex::new(String::new()),
        approval_notice_mode: Mutex::new(APPROVAL_NOTICE_INTERRUPT.to_string()),
        notification_language: Mutex::new("en".to_string()),
        preferred_monitor: Mutex::new(None),
        global_shortcuts: Mutex::new(shortcuts::GlobalShortcutsState::default()),
    }
}
